### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by leondutoit** [freenas/py-pf#1]
Hi

This is a really interesting library. I work at the University of Oslo's Center for IT, and I would like to experiment with it, to give more dynamism and structure to our pf firewall management. I notice however, that there is no license accompanying the source code. Would you consider adding one?

Regards
Leon

**Comment by jceel** [comment]
There you go, added a standard 2-clause BSD license. Have fun with the library!

**Comment by leondutoit** [comment]
Awesome, thanks!
